<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Amenity;
use App\Models\Room;
use App\Models\User;
use App\Models\Statistical;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        User::insert([
            "name"=>"test",
            "email"=>"test@test.test",
            "password"=>bcrypt("test"),
            "role"=>"admin",
            "created_at"=>now(),
        ]);
        Category::Insert([
            ["name" => "Phòng view đẹp","created_at"=>now()],
            ["name" => "Phòng gia đình","created_at"=>now()],
            ["name" => "Phòng Tổng Thống","created_at"=>now()],
            ["name" => "Phòng bình dân","created_at"=>now()],
            ["name" => "Phòng Vip","created_at"=>now()],
        ]);
        
        Amenity::Insert([[
            "name"=> "Bữa sáng miễn phí",
            "created_at" => now(),
        ],[
            "name"=> "Có bãi đỗ xe",
            "created_at" => now(),
        ],[
            "name"=> "Wifi miễn phí",
            "created_at" => now(),
        ],[
            "name"=> "Máy lạnh",
            "created_at" => now(),
        ],[
            "name"=> "Bồn tắm",
            "created_at" => now(),
        ],[
            "name"=>"Có phòng gym",
            "created_at"=>now(),
        ]]);
        Room::insert([
            [
                "name" => "Phòng 1",
                "code" => "1",
                "floor" => "1",
                "requirements" => "1",
                "status" => "1",
                "category_id" => "1",
                "pimage" => "1",
                "description" => "1",
                "base_price" => "1",
                "room_area" => "1",
                "bathroom_area" => "1",
                "max_guests" => "1",
                "bed_count" => "1",
                "amenities" => "1",
                "old_img" => "1",
                "created_at" => now(),
            ],
            [
                "name" => "Phòng 2",
                "code" => "2",
                "floor" => "2",
                "requirements" => "2",
                "status" => "2",
                "category_id" => "2",
                "pimage" => "2",
                "description" => "2",
                "base_price" => "2",
                "room_area" => "2",
                "bathroom_area" => "2",
                "max_guests" => "2",
                "bed_count" => "2",
                "amenities" => "2",
                "old_img" => "2",
                "created_at" => now(),
            ],
            [
                "name" => "Phòng 3",
                "code" => "3",
                "floor" => "3",
                "requirements" => "3",
                "status" => "3",
                "category_id" => "3",
                "pimage" => "3",
                "description" => "3",
                "base_price" => "3",
                "room_area" => "3",
                "bathroom_area" => "3",
                "max_guests" => "3",
                "bed_count" => "3",
                "amenities" => "3",
                "old_img" => "3",
                "created_at" => now(),
            ],
            [
                "name" => "Phòng 4",
                "code" => "4",
                "floor" => "4",
                "requirements" => "4",
                "status" => "4",
                "category_id" => "4",
                "pimage" => "4",
                "description" => "4",
                "base_price" => "4",
                "room_area" => "4",
                "bathroom_area" => "4",
                "max_guests" => "4",
                "bed_count" => "4",
                "amenities" => "4",
                "old_img" => "4",
                "created_at" => now(),
            ],
            
            [
                "name" => "Phòng 5",
                "code" => "5",
                "floor" => "5",
                "requirements" => "5",
                "status" => "5",
                "category_id" => "5",
                "pimage" => "5",
                "description" => "5",
                "base_price" => "5",
                "room_area" => "5",
                "bathroom_area" => "5",
                "max_guests" => "5",
                "bed_count" => "5",
                "amenities" => "5",
                "old_img" => "5",
                "created_at" => now(),
            ],
            [
                "name" => "Phòng 6",
                "code" => "6",
                "floor" => "6",
                "requirements" => "6",
                "status" => "6",
                "category_id" => "2",
                "pimage" => "6",
                "description" => "6",
                "base_price" => "6",
                "room_area" => "6",
                "bathroom_area" => "6",
                "max_guests" => "6",
                "bed_count" => "6",
                "amenities" => "6",
                "old_img" => "6",
                "created_at" => now(),
            ],
            [
                "name" => "Phòng 7",
                "code" => "7",
                "floor" => "7",
                "requirements" => "7",
                "status" => "7",
                "category_id" => "1",
                "pimage" => "7",
                "description" => "7",
                "base_price" => "7",
                "room_area" => "7",
                "bathroom_area" => "7",
                "max_guests" => "7",
                "bed_count" => "7",
                "amenities" => "7",
                "old_img" => "7",
                "created_at" => now(),
            ],
            [
                "name" => "Phòng 8",
                "code" => "8",
                "floor" => "8",
                "requirements" => "8",
                "status" => "8",
                "category_id" => "4",
                "pimage" => "8",
                "description" => "8",
                "base_price" => "8",
                "room_area" => "8",
                "bathroom_area" => "8",
                "max_guests" => "8",
                "bed_count" => "8",
                "amenities" => "8",
                "old_img" => "8",
                "created_at" => now(),
            ],
            [
                "name" => "Phòng 9",
                "code" => "9",
                "floor" => "9",
                "requirements" => "9",
                "status" => "9",
                "category_id" => "1",
                "pimage" => "9",
                "description" => "9",
                "base_price" => "9",
                "room_area" => "9",
                "bathroom_area" => "9",
                "max_guests" => "9",
                "bed_count" => "9",
                "amenities" => "9",
                "old_img" => "9",
                "created_at" => now(),
            ],
            [
                "name" => "Phòng 10",
                "code" => "10",
                "floor" => "10",
                "requirements" => "10",
                "status" => "10",
                "category_id" => "5",
                "pimage" => "10",
                "description" => "10",
                "base_price" => "10",
                "room_area" => "10",
                "bathroom_area" => "10",
                "max_guests" => "10",
                "bed_count" => "10",
                "amenities" => "10",
                "old_img" => "10",
                "created_at" => now(),
            ],
        ]);
        Statistical::insert([
            [
                'date' => now()->subDays(7)->toDateString(),
                'total_bookings' => 15,
                'total_customers' => 12,
                'total_revenue' => 25000000,
                'rooms_occupied' => 8,
                'rooms_available' => 32,
                'created_at' => now()->subDays(7),
                'updated_at' => now()->subDays(7),
            ],
            [
                'date' => now()->subDays(6)->toDateString(),
                'total_bookings' => 22,
                'total_customers' => 18,
                'total_revenue' => 32000000,
                'rooms_occupied' => 12,
                'rooms_available' => 28,
                'created_at' => now()->subDays(6),
                'updated_at' => now()->subDays(6),
            ],
            [
                'date' => now()->subDays(5)->toDateString(),
                'total_bookings' => 18,
                'total_customers' => 15,
                'total_revenue' => 28000000,
                'rooms_occupied' => 10,
                'rooms_available' => 30,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],
            [
                'date' => now()->subDays(4)->toDateString(),
                'total_bookings' => 25,
                'total_customers' => 20,
                'total_revenue' => 38000000,
                'rooms_occupied' => 15,
                'rooms_available' => 25,
                'created_at' => now()->subDays(4),
                'updated_at' => now()->subDays(4),
            ],
            [
                'date' => now()->subDays(3)->toDateString(),
                'total_bookings' => 20,
                'total_customers' => 16,
                'total_revenue' => 30000000,
                'rooms_occupied' => 12,
                'rooms_available' => 28,
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(3),
            ],
            [
                'date' => now()->subDays(2)->toDateString(),
                'total_bookings' => 28,
                'total_customers' => 22,
                'total_revenue' => 42000000,
                'rooms_occupied' => 18,
                'rooms_available' => 22,
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'date' => now()->subDays(1)->toDateString(),
                'total_bookings' => 24,
                'total_customers' => 19,
                'total_revenue' => 36000000,
                'rooms_occupied' => 14,
                'rooms_available' => 26,
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subDays(1),
            ],
            [
                'date' => now()->toDateString(),
                'total_bookings' => 16,
                'total_customers' => 13,
                'total_revenue' => 24000000,
                'rooms_occupied' => 9,
                'rooms_available' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
